const PRODUCTS_DATA = [
    { id: "alveolair-sir", name: "Alveolair Sir", price: 18.50, category: "Respiratory", moa: "Βλεννολυτική δράση μέσω διάσπασης δισουλφιδικών δεσμών. Ενισχύει την κροσσωτή κάθαρση.", formula: "N-Acetylcysteine 600mg, Hedera Helix 10%, Thymus Vulgaris." },
    { id: "z-boost", name: "Z-boost Immune", price: 24.90, category: "Immune", moa: "Ενεργοποίηση NK-κυττάρων και ενίσχυση φαγοκυττάρωσης μέσω του άξονα Ψευδαργύρου-Βιταμίνης C.", formula: "Liposomal Vit-C 1000mg, Zinc Picolinate, Propolis." },
    { id: "zplast", name: "Zplast Hydrogel", price: 12.00, category: "Wound Care", moa: "Υγρό περιβάλλον επούλωσης και αντιμικροβιακός φραγμός με ιόντα αργύρου $Ag^+$.", formula: "Hydrocolloid Matrix, Ionic Silver." },
    { id: "bruise-off", name: "Bruise Off Gel", price: 15.80, category: "Topical", moa: "Μείωση διαπερατότητας τριχοειδών και απορρόφηση αιματωμάτων.", formula: "Arnica Montana 10%, Escin, Bromelain." },
    { id: "d-vit-5000", name: "D-vit 5000iu Gold", price: 19.20, category: "Supplements", moa: "Ρύθμιση VDR υποδοχέα και ενίσχυση ενδογενούς παραγωγής καθελισιδινών.", formula: "Cholecalciferol $D_3$, Olive Oil, Vitamin $K_2$ MK7." },
    { id: "z-mag-triple", name: "Z-Mag Triple Action", price: 21.50, category: "Muscle", moa: "Συνδυαστική δράση 3 μορφών μαγνησίου για πλήρη κυτταρική κάλυψη (Bisglycinate, Citrate, Malate).", formula: "Magnesium Complex + Vit-$B_6$ active." },
    { id: "omega3-ultra", name: "Omega-3 Ultra Pure", price: 32.00, category: "Cardio", moa: "Μείωση τριγλυκεριδίων και προστασία ενδοθηλίου μέσω υψηλής συγκέντρωσης EPA/DHA.", formula: "Fish Oil 1200mg (EPA 500 / DHA 250)." },
    { id: "probio-max", name: "Probio-Max 50B", price: 28.50, category: "Digestive", moa: "Αποκατάσταση μικροβιώματος και ενίσχυση εντερικού φραγμού.", formula: "12 Προβιοτικά στελέχη, 50 Billion CFU." },
    { id: "joint-fix", name: "Joint-Fix Collagen", price: 35.00, category: "Joints", moa: "Διέγερση παραγωγής κολλαγόνου τύπου ΙΙ και μείωση φλεγμονής χόνδρου.", formula: "Hydrolyzed Collagen peptides, Glucosamine, Chondroitin." },
    { id: "sleep-well", name: "Sleep-Well Melatonin", price: 14.50, category: "CNS", moa: "Ρύθμιση κιρκάδιου ρυθμού και μείωση χρόνου έλευσης ύπνου.", formula: "Melatonin 1mg, Valeriana, Passiflora." },
    { id: "iron-fe", name: "Iron-Fe Bisglycinate", price: 17.00, category: "Blood", moa: "Αύξηση φερριτίνης χωρίς οξείδωση εντέρου και δυσκοιλιότητα.", formula: "Ferrous Bisglycinate 25mg, Vit-C." },
    { id: "b-complex-act", name: "B-Complex Active", price: 22.00, category: "Energy", moa: "Υποστήριξη μεταβολισμού ATP και λειτουργίας νευροδιαβιβαστών.", formula: "Full B-Spectrum in Active Forms." },
    { id: "eye-protect", name: "Eye-Protect Lutein", price: 26.00, category: "Vision", moa: "Προστασία ωχράς κηλίδας από μπλε φως και οξείδωση.", formula: "Lutein 20mg, Zeaxanthin 4mg, Astaxanthin." },
    { id: "hepa-clean", name: "Hepa-Clean Silymarin", price: 23.50, category: "Liver", moa: "Αποτοξίνωση ηπατοκυττάρων και προστασία από λιπώδη διήθηση.", formula: "Milk Thistle 80% Silymarin, Artichoke." },
    { id: "hair-skin", name: "Hair-Skin-Nails", price: 19.80, category: "Beauty", moa: "Ενίσχυση δομής κερατίνης και κολλαγόνου στα εξαρτήματα δέρματος.", formula: "Biotin 10000mcg, Zinc, L-Cysteine." },
    { id: "antiox-coq10", name: "Antiox-CoQ10", price: 29.00, category: "Energy", moa: "Βελτίωση μιτοχονδριακής παραγωγής ενέργειας και καρδιοπροστασία.", formula: "Coenzyme $Q_{10}$ 200mg, Vit-E." },
    { id: "calm-ashwa", name: "Calm-Ashwagandha", price: 21.00, category: "CNS", moa: "Προσαρμογόνος δράση που μειώνει τα επίπεδα κορτιζόλης.", formula: "KSM-66 Ashwagandha, Magnesium." },
    { id: "vit-k2-mk7", name: "Vitamin $K_2$-MK7", price: 18.00, category: "Bone", moa: "Ενεργοποίηση οστεοκαλσίνης για εναπόθεση ασβεστίου στα οστά.", formula: "Vitamin $K_2$ as MK-7 100mcg." },
    { id: "kids-multi", name: "Kids-Multi Jelly", price: 16.50, category: "Pediatric", moa: "Κάλυψη διατροφικών κενών για ανάπτυξη σκελετού και εγκεφάλου.", formula: "Multi-vitamins, Iodine, Zinc (Sugar-Free)." }
];
