const products=[{name:'Z-DermAspis',price:5.03},{name:'ZplastCream 40gr',price:12.3},{name:'ZplastCream 100gr',price:24.79},{name:'Bruise Off Bite Out & Pain Free cream',price:5.26},{name:'Z-boost 30 caps',price:14.93},{name:'Z-boost 12 caps',price:6.99},{name:'Zarkolia Cosmetic pack',price:23.89},{name:'Hydralia Face cream 50ml',price:8.9},{name:'Revitacell + Face cream 50ml',price:10.69},{name:'Revitace Eyes cream Luce 30ml',price:10.1},{name:'Alveolair Sir',price:7.65}];
const productDetails=[{id:'alveolair',name:'Alveol Air Φυτικό Σιρόπι',image:'URL_ΕΙΚΟΝΑΣ_ΣΙΡΟΠΙΟΥ_ΕΔΩ',description:`<h3>Φυτικό Σιρόπι για Βήχα</h3><p>Το φυτικό σιρόπι για βήχα είναι η ιδανική λύση για την ανακούφιση από ξηρό ή παραγωγικό βήχα...</p>`},{id:'revitacell_plus',name:'Revitacell Plus',image:'URL_ΕΙΚΟΝΑΣ_REVITACELL_PLUS_ΕΔΩ',description:`<h3>Προηγμένη Αντιρυτιδική Κρέμα Σύσφιξης</h3><p>Η Zarkolia Revitacell Plus είναι μια προηγμένη αντιρυτιδική κρέμα σύσφιξης...</p>`},{id:'revitacell_eyes',name:'Revitacell Eyes Luce',image:'URL_ΕΙΚΟΝΑΣ_EYES_LUCE_ΕΔΩ',description:`<h3>Επανορθωτική Κρέμα Ματιών</h3><p>Η Επανορθωτική Κρέμα Ματιών μειώνει μαύρους κύκλους...</p>`},{id:'hydralia',name:'Hydralia Face Cream',image:'URL_ΕΙΚΟΝΑΣ_HYDRALIA_ΕΔΩ',description:`<h3>Υπέρ Ενυδατική Κρέμα Προσώπου</h3><p>Η ενυδατική κρέμα Hydralia της Zarkolia...</p>`},{id:'zplast',name:'Zplast Cream',image:'URL_ΕΙΚΟΝΑΣ_ZPLAST_ΕΔΩ',description:`<h3>Αναπλαστική Κρέμα για Επούλωση</h3><p>Η Zplast Cream προσφέρει άμεση βοήθεια...</p>`},{id:'boost_caps',name:'Z-Boost Caps',image:'URL_ΕΙΚΟΝΑΣ_BOOST_CAPS_ΕΔΩ',description:`<h3>Συμπλήρωμα για το Ανοσοποιητικό</h3><p>Ανακαλύψτε το Z-Boost...</p>`},{id:'cosmetic_pack',name:'Zarkolia Cosmetic Pack',image:'URL_ΕΙΚΟΝΑΣ_PACK_ΕΔΩ',description:`<h3>Πακέτο Περιποίησης Zarkolia</h3><p>Το πακέτο περιλαμβάνει τις κρέμες Hydralia, Revitacell και Revitacell Eyes Luce...</p>`}];

document.addEventListener("DOMContentLoaded",function(){
    document.getElementById('productModal').innerHTML=`<div class="modal-content"><div class="modal-header"><h2 id="modalProductName"></h2><span class="close-button" onclick="closeProductModal()">&times;</span></div><div class="modal-body"><img id="modalProductImage" src="" alt="Product Image"><div id="modalProductDescription"></div></div></div>`;
    document.getElementById('previewModal').innerHTML=`<div class="modal-content"><div class="modal-header"><h2>Προεπισκόπηση</h2><span class="close-button" onclick="closePreviewModal()">&times;</span></div><div class="modal-body"><pre id="previewContent"></pre></div><div class="modal-footer"><button id="saveTxtButton" class="btn" style="background-color:#5cb85c">Αποθήκευση</button><button class="btn" style="background-color:#aaa" onclick="closePreviewModal()">Κλείσιμο</button></div></div>`;
    const g=document.getElementById('productGallery');productDetails.forEach(p=>{const c=document.createElement('div');c.className='product-card';c.onclick=()=>showProductDetails(p.id);c.innerHTML=`<img src="${p.image}" alt="${p.name}"><h4>${p.name}</h4>`;g.appendChild(c);});
    const t=document.querySelector('#product-table tbody');products.forEach(p=>{const r=document.createElement('tr');r.innerHTML=`<td>${p.name}</td><td>${p.price.toFixed(2)} €</td><td><input type="number" class="quantity" min="0" data-price="${p.price}" oninput="updateAll()" value="0"></td><td class="gifts">0</td><td class="effective-price normal">${p.price.toFixed(2)} €</td><td class="line-total">0.00 €</td>`;t.appendChild(r);});
    updateAll();
});
function showProductDetails(id){const p=productDetails.find(p=>p.id===id);if(p){document.getElementById('modalProductName').textContent=p.name;document.getElementById('modalProductImage').src=p.image;document.getElementById('modalProductDescription').innerHTML=p.description;document.getElementById('productModal').style.display='block';}}
function closeProductModal(){document.getElementById('productModal').style.display='none';}
function closePreviewModal(){document.getElementById('previewModal').style.display='none';}
function calculateGifts(q){if(q<9)return 0;if(q>=9&&q<18)return 1;if(q>=18&&q<24)return 3;if(q>=24&&q<48)return 6;const r=15/48;return Math.floor(q*r);}
function updateAll(){let t=0;document.querySelectorAll("#product-table tbody tr").forEach(r=>{const q=r.querySelector(".quantity"),p=parseInt(q.value)||0,d=parseFloat(q.dataset.price),g=calculateGifts(p),a=p+g,l=p*d;let e=d;p>0&&a>0&&(e=l/a);const pc=r.querySelector(".effective-price");pc.innerHTML=`${e.toFixed(2)} €`;if(e<d-0.001){pc.classList.add('discounted');pc.classList.remove('normal');}else{pc.classList.add('normal');pc.classList.remove('discounted');}r.querySelector(".gifts").textContent=g;r.querySelector(".line-total").innerHTML=`${l.toFixed(2)} €`;t+=l;});const v=t*0.24,f=t+v;document.getElementById("net-value").innerHTML=`${t.toFixed(2)} €`;document.getElementById("vat-value").innerHTML=`${v.toFixed(2)} €`;document.getElementById("final-total").innerHTML=`${f.toFixed(2)} €`;}
function getOrderData(){const c={eponimia:document.getElementById("eponimia").value,afm:document.getElementById("afm").value,doy:document.getElementById("doy").value,mobile:document.getElementById("mobile").value,phone:document.getElementById("phone").value,email:document.getElementById("email").value};const i=[];document.querySelectorAll("#product-table tbody tr").forEach(r=>{const q=parseInt(r.querySelector('.quantity').value)||0;q>0&&i.push({name:r.cells[0].textContent,quantity:q,gifts:parseInt(r.querySelector('.gifts').textContent),effectivePrice:r.querySelector('.effective-price').textContent,total:r.querySelector('.line-total').textContent});});return{customerData:c,items:i,totals:{net:document.getElementById("net-value").textContent,vat:document.getElementById("vat-value").textContent,final:document.getElementById("final-total").textContent}}}
function generateOrderContent(){const{customerData:c,items:i,totals:t}=getOrderData();const b="\n\nΣΤΟΙΧΕΙΑ ΚΑΤΑΘΕΣΗΣ\n----------------------------------------\nIBAN: GR8901722520005252016160277\nΤράπεζα: Τράπεζα Πειραιώς\n";let content="========================================\n      Π Α Ρ Α Γ Γ Ε Λ Ι Α\n========================================\n\n";content+="ΣΤΟΙΧΕΙΑ ΠΕΛΑΤΗ\n----------------------------------------\n";content+=`Επωνυμία: ${c.eponimia}\nΑΦΜ: ${c.afm}\nΔΟΥ: ${c.doy}\n`;content+=`Email: ${c.email}\nΤηλ: ${c.mobile} / ${c.phone}\n\n`;content+="ΑΝΑΛΥΣΗ ΠΑΡΑΓΓΕΛΙΑΣ\n------------------------------------------------------------------------\n";i.forEach(item=>{let qText=item.gifts>0?`${item.quantity} (+${item.gifts} Δώρο)`:`${item.quantity}`;content+=`${item.name}\n`;content+=`  └─ Ποσότητα: ${qText.padEnd(15)} | Τελ. Τιμή/Τεμ.: ${item.effectivePrice.padEnd(12)} | Σύνολο: ${item.total.padStart(8)}\n\n`;});content+="------------------------------------------------------------------------\n\n";content+="ΣΥΝΟΛΑ\n----------------------------------------\n";content+=`Καθαρή Αξία:${''.padStart(15)} ${t.net}\n`;content+=`Αξία ΦΠΑ (24%):${''.padStart(11)} ${t.vat}\n`;content+=`ΤΕΛΙΚΟ ΠΟΣΟ:${''.padStart(14)} ${t.final}\n`;content+=b;return content;}
function sendEmailViaClient(){const{customerData:c,items:i}=getOrderData();if(i.length===0){alert("Η παραγγελία είναι κενή.");return}const body=generateOrderContent();const subject=`Νέα Παραγγελία από ${c.eponimia||'Νέος Πελάτης'}`;let mailtoLink=`mailto:pzaro2010@gmail.com,liapaki2017@gmail.com`;c.email&&(mailtoLink+=`?cc=${c.email}`);mailtoLink+=`&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;window.location.href=mailtoLink;}
function previewAndSaveAsTXT(){if(getOrderData().items.length===0){alert("Η παραγγελία είναι κενή.");return}const content=generateOrderContent();const filename=`Παραγγελία_${getOrderData().customerData.eponimia.replace(/\s/g,'_')||'customer'}.txt`;document.getElementById('previewContent').textContent=content;document.getElementById('previewModal').style.display='block';document.getElementById('saveTxtButton').onclick=()=>saveTextAsFile(content,filename);}
function saveTextAsFile(text,filename){const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=filename;document.body.appendChild(link);link.click();document.body.removeChild(link);closePreviewModal();}
function clearForm(){document.getElementById("orderForm").reset();document.querySelectorAll(".quantity").forEach(q=>{q.value="0"});updateAll();}
