const products=[{name:'Z-DermAspis',price:5.03},{name:'ZplastCream 40gr',price:12.3},{name:'ZplastCream 100gr',price:24.79},{name:'Bruise Off Bite Out & Pain Free cream',price:5.26},{name:'Z-boost 30 caps',price:14.93},{name:'Z-boost 12 caps',price:6.99},{name:'Zarkolia Cosmetic pack',price:23.89},{name:'Hydralia Face cream 50ml',price:8.9},{name:'Revitacell + Face cream 50ml',price:10.69},{name:'Revitace Eyes cream Luce 30ml',price:10.1},{name:'Alveolair Sir',price:7.65}];

const productDetails=[
    {id:'Alveolair Sir',name:'Alveolair Sir',description:`<h3>Φυτικό Σιρόπι για Βήχα</h3><p>Το φυτικό σιρόπι για βήχα είναι η ιδανική λύση για την ανακούφιση από ξηρό ή παραγωγικό βήχα. Η μοναδική του σύνθεση μαλακώνει τον ερεθισμένο αεραγωγό, ενώ ενισχύει την υγεία του λαιμού και του αναπνευστικού συστήματος.</p><h3>Βασικά Συστατικά και Οφέλη</h3><p><strong>Ευκάλυπτος:</strong> Παρέχει αντιφλεγμονώδεις και αντισηπτικές ιδιότητες.<br><strong>Θυμάρι:</strong> Διαθέτει ισχυρές αντιβακτηριακές ιδιότητες.<br><strong>Αλθέα:</strong> Καταπραΰνει την ευαίσθητη περιοχή του λαιμού.<br><strong>Κράνι και Berries:</strong> Πλούσια σε αντιοξειδωτικά.<br><strong>Ιπποφαές:</strong> Υψηλή συγκέντρωση βιταμίνης C.</p>`},
    {id:'Revitacell + Face cream 50ml',name:'Revitacell + Face cream 50ml',description:`<h3>Προηγμένη Αντιρυτιδική Κρέμα Σύσφιξης</h3><p>Η Zarkolia Revitacell Plus είναι μια προηγμένη αντιρυτιδική κρέμα σύσφιξης για ολική επανόρθωση. Η πλούσια σύνθεσή της με Μαστίχα Χίου, Έλαιο Ροδιού και Super Berries προσφέρει ισχυρή αντιοξειδωτική προστασία κατά της πρόωρης γήρανσης.</p><p>Ως κρέμα με υαλουρονικό οξύ, ενυδατώνει σε βάθος και “γεμίζει” τις λεπτές γραμμές, ενώ η Αλόη καταπραΰνει την επιδερμίδα. Προσφέρει ορατό αποτέλεσμα lifting, αφήνοντας το δέρμα λείο, σφριγηλό και νεανικό.</p>`},
    {id:'Revitace Eyes cream Luce 30ml',name:'Revitace Eyes cream Luce 30ml',description:`<h3>Επανορθωτική Κρέμα Ματιών</h3><p>Η Επανορθωτική Κρέμα Ματιών μειώνει μαύρους κύκλους, πρήξιμο και ρυτίδες γύρω από τα μάτια. Με Ιπποκαστανιά και Άρνικα, προσφέρει αντιοξειδωτική προστασία και καταπραΰνει την περιοχή.</p><p>Το Υαλουρονικό Οξύ ενυδατώνει και αυξάνει τη σφριγηλότητα του δέρματος, ενώ τα φυσικά έλαια θρέφουν την επιδερμίδα.</p>`},
    {id:'Hydralia Face cream 50ml',name:'Hydralia Face cream 50ml',description:`<h3>Υπέρ Ενυδατική Κρέμα Προσώπου</h3><p>Η ενυδατική κρέμα Hydralia της Zarkolia προσφέρει μια πλούσια, ενυδατική φόρμουλα που ενυδατώνει βαθιά την επιδερμίδα, προσδίδοντας απαλή υφή και αναζωογόνηση. Δροσίζει το πρόσωπο άμεσα και αποκαθιστά τη φυσιολογική υγρασία της επιδερμίδας.</p><p>Εμπλουτισμένη με Έλαια Αβοκάντο, Jojoba & Αμυγδάλου, Υαλουρονικό Οξύ και Αλόη, προσφέρει εντατική προστασία ενάντια στην αφυδάτρωση.</p>`},
    {id:'ZplastCream 40gr',name:'ZplastCream 40gr',description:`<h3>Αναπλαστική Κρέμα για Επούλωση</h3><p>Η Zplast Cream προσφέρει άμεση βοήθεια σε καταστάσεις όπως κάψιμο από τον ήλιο, εγκαύματα και φυσαλίδες. Λειτουργεί ως μία ισχυρή αναπλαστική κρέμα για ουλές, καθώς επιταχύνει τη διαδικασία της επούλωσης.</p><p>Με φυσικά συστατικά όπως το μέλι, η μαστίχα Χίου και επιλεγμένα ελληνικά βότανα, καταπολεμά βακτήρια, μειώνει τις φλεγμονές και ενυδατώνει το δέρμα.</p>`},
    {id:'Z-boost 30 caps',name:'Z-boost 30 caps',description:`<h3>Συμπλήρωμα για την Ενίσχυση του Ανοσοποιητικού</h3><p>Ανακαλύψτε το Z-Boost, το εξειδικευμένο συμπλήρωμα διατροφής που ενισχύει την άμυνα του οργανισμού σας! Με έναν ισχυρό συνδυασμό αντιοξειδωτικών συστατικών, όπως το άλφα-λιποϊκό οξύ και το συνένζυμο Q10, το Z-Boost προστατεύει τον οργανισμό από καθημερινές απειλές.</p><h3>Βασικά Συστατικά</h3><p>Το Z-Boost περιέχει έναν μοναδικό συνδυασμό αντιοξειδωτικών: άλφα-λιποϊκό οξύ, συνένζυμο Q10, ακετυλοκυστεΐνη, ψευδάργυρο και σελήνιο.</p><p><em>Διαθέσιμο σε συσκευασίες με 12 και 30 κάψουλες.</em></p>`},
    {id:'Zarkolia Cosmetic pack',name:'Zarkolia Cosmetic pack',description:`<h3>Πακέτο Περιποίησης Zarkolia</h3><p>Το πακέτο περιλαμβάνει τις κρέμες Hydralia, Revitacell και Revitacell Eyes Luce για μια ολοκληρωμένη φροντίδα ενυδάτωσης και αντιγήρανσης προσώπου και ματιών.</p>`}
];

document.addEventListener("DOMContentLoaded", function() {
    const productButtonsContainer = document.getElementById('productButtonsContainer');
    products.forEach(p => {
        const button = document.createElement('button');
        button.className = 'product-btn';
        button.textContent = p.name;
        button.onclick = () => showProductDetails(p.name);
        productButtonsContainer.appendChild(button);
    });
    
    document.getElementById('productModal').innerHTML = `<div class="modal-content"><div class="modal-header"><h2 id="modalProductName"></h2><span class="close-button" onclick="closeProductModal()">&times;</span></div><div class="modal-body"><div id="modalProductDescription"></div></div></div>`;
    document.getElementById('previewModal').innerHTML = `<div class="modal-content"><div class="modal-header"><h2>Προεπισκόπηση</h2><span class="close-button" onclick="closePreviewModal()">&times;</span></div><div class="modal-body"><pre id="previewContent"></pre></div><div class="modal-footer"><button id="saveTxtButton" class="btn" style="background-color:#5cb85c">Αποθήκευση</button><button class="btn" style="background-color:#aaa" onclick="closePreviewModal()">Κλείσιμο</button></div></div>`;
    
    const tableBody=document.querySelector('#product-table tbody');
    products.forEach(p=>{const r=document.createElement('tr');r.innerHTML=`<td>${p.name}</td><td>${p.price.toFixed(2)} €</td><td><input type="number" class="quantity" min="0" data-price="${p.price}" oninput="updateAll()" value="0"></td><td class="gifts">0</td><td class="effective-price normal">${p.price.toFixed(2)} €</td><td class="line-total">0.00 €</td>`;tableBody.appendChild(r);});
    
    updateAll();
});

function showProductDetails(productName){
    const p=productDetails.find(p=>p.name===productName);
    if(p){
        document.getElementById('modalProductName').textContent = p.name;
        document.getElementById('modalProductDescription').innerHTML = p.description;
        document.getElementById('productModal').style.display='block';
    } else {
        // Fallback for products in the table but not in the details list
        document.getElementById('modalProductName').textContent = productName;
        document.getElementById('modalProductDescription').innerHTML = `<p>Δεν βρέθηκε αναλυτική περιγραφή για αυτό το προϊόν.</p>`;
        document.getElementById('productModal').style.display='block';
    }
}
function closeProductModal(){document.getElementById('productModal').style.display='none';}
function closePreviewModal(){document.getElementById('previewModal').style.display='none';}

function calculateGifts(quantity){if(quantity<9)return 0;if(quantity>=9&&quantity<18)return 1;if(quantity>=18&&quantity<24)return 3;if(quantity>=24&&quantity<48)return 6;const ratio=15/48;return Math.floor(quantity*ratio);}
function updateAll(){let t=0;document.querySelectorAll("#product-table tbody tr").forEach(r=>{const q=r.querySelector(".quantity"),p=parseInt(q.value)||0,d=parseFloat(q.dataset.price),g=calculateGifts(p),a=p+g,l=p*d;let e=d;p>0&&a>0&&(e=l/a);const pc=r.querySelector(".effective-price");pc.innerHTML=`${e.toFixed(2)} €`;if(e<d-0.001){pc.classList.add('discounted');pc.classList.remove('normal');}else{pc.classList.add('normal');pc.classList.remove('discounted');}r.querySelector(".gifts").textContent=g;r.querySelector(".line-total").innerHTML=`${l.toFixed(2)} €`;t+=l;});const v=t*0.24,f=t+v;document.getElementById("net-value").innerHTML=`${t.toFixed(2)} €`;document.getElementById("vat-value").innerHTML=`${v.toFixed(2)} €`;document.getElementById("final-total").innerHTML=`${f.toFixed(2)} €`;}
function getOrderData(){const c={eponimia:document.getElementById("eponimia").value,afm:document.getElementById("afm").value,doy:document.getElementById("doy").value,mobile:document.getElementById("mobile").value,phone:document.getElementById("phone").value,email:document.getElementById("email").value};const i=[];document.querySelectorAll("#product-table tbody tr").forEach(r=>{const q=parseInt(r.querySelector('.quantity').value)||0;q>0&&i.push({name:r.cells[0].textContent,quantity:q,gifts:parseInt(r.querySelector('.gifts').textContent),effectivePrice:r.querySelector('.effective-price').textContent,total:r.querySelector('.line-total').textContent});});return{customerData:c,items:i,totals:{net:document.getElementById("net-value").textContent,vat:document.getElementById("vat-value").textContent,final:document.getElementById("final-total").textContent}}}
function generateOrderContent(){const{customerData:c,items:i,totals:t}=getOrderData();const b="\n\nΣΤΟΙΧΕΙΑ ΚΑΤΑΘΕΣΗΣ\n----------------------------------------\nIBAN: GR8901722520005252016160277\nΤράπεζα: Τράπεζα Πειραιώς\n";let content="========================================\n      Π Α Ρ Α Γ Γ Ε Λ Ι Α\n========================================\n\n";content+="ΣΤΟΙΧΕΙΑ ΠΕΛΑΤΗ\n----------------------------------------\n";content+=`Επωνυμία: ${c.eponimia}\nΑΦΜ: ${c.afm}\nΔΟΥ: ${c.doy}\n`;content+=`Email: ${c.email}\nΤηλ: ${c.mobile} / ${c.phone}\n\n`;content+="ΑΝΑΛΥΣΗ ΠΑΡΑΓΓΕΛΙΑΣ\n------------------------------------------------------------------------\n";i.forEach(item=>{let qText=item.gifts>0?`${item.quantity} (+${item.gifts} Δώρο)`:`${item.quantity}`;content+=`${item.name}\n`;content+=`  └─ Ποσότητα: ${qText.padEnd(15)} | Τελ. Τιμή/Τεμ.: ${item.effectivePrice.padEnd(12)} | Σύνολο: ${item.total.padStart(8)}\n\n`;});content+="------------------------------------------------------------------------\n\n";content+="ΣΥΝΟΛΑ\n----------------------------------------\n";content+=`Καθαρή Αξία:${''.padStart(15)} ${t.net}\n`;content+=`Αξία ΦΠΑ (24%):${''.padStart(11)} ${t.vat}\n`;content+=`ΤΕΛΙΚΟ ΠΟΣΟ:${''.padStart(14)} ${t.final}\n`;content+=b;return content;}
function sendEmailViaClient(){const{customerData:c,items:i}=getOrderData();if(i.length===0){alert("Η παραγγελία είναι κενή.");return}const body=generateOrderContent();const subject=`Νέα Παραγγελία από ${c.eponimia||'Νέος Πελάτης'}`;let mailtoLink=`mailto:pzaro2010@gmail.com,liapaki2017@gmail.com`;c.email&&(mailtoLink+=`?cc=${c.email}`);mailtoLink+=`&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;window.location.href=mailtoLink;}
function previewAndSaveAsTXT(){if(getOrderData().items.length===0){alert("Η παραγγελία είναι κενή.");return}const content=generateOrderContent();const filename=`Παραγγελία_${getOrderData().customerData.eponimia.replace(/\s/g,'_')||'customer'}.txt`;document.getElementById('previewContent').textContent=content;document.getElementById('previewModal').style.display='block';document.getElementById('saveTxtButton').onclick=()=>saveTextAsFile(content,filename);}
function saveTextAsFile(text,filename){const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=filename;document.body.appendChild(link);link.click();document.body.removeChild(link);closePreviewModal();}
function clearForm(){document.getElementById("orderForm").reset();document.querySelectorAll(".quantity").forEach(q=>{q.value="0"});updateAll();}
